### ISSUE TITLE
[BUG] Error when placing Compat NASA Workbench

### ISSUE THREAD

**Issue by TheMCSpacePro** [flyingperson23/GalacticraftGravity#1]
With GC version 4.0.6, I get this error when also using your addon:
https://mclo.gs/xmoGlXr

According to one of the GC contributors, it might be because you re-register all of GC4's stuff for some reason but forgot to register the compact workbench.

**Comment by TheMCSpacePro** [comment]
(The error starts at line 6962)

**Comment by JustAPotota** [comment]
> According to one of the GC contributors, it might be because you re-register all of GC4's stuff for some reason but forgot to register the compact workbench.

GC5 contributor specifically. I'm not familiar with Forge 1.12 modding, but it looks like it should be registering `TileEntityCompactNasaWorkbench` [here](https://github.com/flyingperson23/GalacticraftGravity/blob/8160d2fef991b8b626f533593c25824d60965119/src/main/java/gcg/AsmHandler.java#L196) to match [GC4's version](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/acec4429525eb30452298c2034d1e5d5d4b41046/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L740).

**Comment by TheMCSpacePro** [comment]
Okay, so it's been a while since this was opened. I'm seeing if this is all that is needed, and if it is, will make a pull request.

**Comment by flyingperson23** [comment]
My bad, sorry it took me so long to look at this. I must've gotten the registration stuff from an older version of GC that didn't have the compact workbench? Anyways, I'll fix it.

**Comment by flyingperson23** [comment]
File has been uploaded
